import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserInfosProvider } from "@/context/UserInfos";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased scroll-smooth w-full overflow-x-hidden`}
      >
        <Toaster 
          position="top-center"
          // style={{
          // }}
        />
        <UserInfosProvider>
          {children}
        </UserInfosProvider>
      </body>
    </html>
  );
}
