import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserInfosProvider } from "@/context/UserInfos";
import { Toaster } from "sonner";
import Header from "@/components/Header";
import { createClient } from "@/utils/supabase/server";
import { getUserCredits } from "@/data/getUserCredits";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const User_Credits = user ? await getUserCredits() : null;
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased scroll-smooth w-full overflow-x-hidden`}
      >
        <Toaster 
          position="top-center"
          // style={{
          // }}
        />
        <UserInfosProvider>
          <Header User_Credits={User_Credits} />
          {children}
        </UserInfosProvider>
      </body>
    </html>
  );
}
